services:
  caddy:
    container_name: odin-caddy
    image: caddy
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  mqtt:
    container_name: odin-mqtt
    image: eclipse-mosquitto
    network_mode: host
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
